### ISSUE TITLE
Upgrade swagger dependencies

### ISSUE THREAD

**Issue by otrosien** [zalando-stups/swagger-codegen-tooling#60]
Update to current versions of swagger libraries:
```
'io.swagger:swagger-codegen:2.2.1'
'io.swagger:swagger-parser:1.0.25'
'io.swagger:swagger-compat-spec-parser:1.0.25'
```

**Comment by jbellmann** [comment]
@otrosien this will be not that easy. I tried it before and experienced a lot of breaking changes. That will be a longer task.

**Comment by otrosien** [comment]
I'll have a look. I hope to improve the situation on transitive dependencies creeping into my gradle build. See here: https://github.com/zalando-incubator/swagger-codegen-gradle-plugin/issues/8
`swagger-codegen` currently pulls in maven-plugin stuff.

**Comment by jbellmann** [comment]
But this deps can be excluded, right?

I will create a branch '0.4.x' for maintenance of current state. Then we can start in 'master' working on updating 'swagger-codegen' dependencies here.

**Comment by otrosien** [comment]
jep, I am excluding the dependencies manually, but that's not how dependencies were intended... Upgrading does not solve the dependencies problem anyway (http://mvnrepository.com/artifact/io.swagger/swagger-codegen/2.2.1)
So, before putting much effort in upgrading, let's discuss issue #61.

**Comment by otrosien** [comment]
I'm trying to fix the issue upstream: https://github.com/swagger-api/swagger-codegen/pull/4840

**Comment by otrosien** [comment]
@jbellmann : undo inclusion of the extra dependencies in https://github.com/zalando-stups/swagger-codegen-tooling/commit/2da1bd5ab77c137ca0ae79823de04f19a0438402#diff-c35b35f47d958c913c8cb108abee5381R23 - we should use the transitive deps from swagger-codegen. If I'm not mistaken there's an incompatible API change in swagger-parser causing gradle run to fail.

**Comment by msymons** [comment]
Edited: 16th July 2017

swagger-codegen v2.2.3 released 15th July 2017. 

@otrosien , Going by the POM, this seems to implement your fix to remove both problem maven-plugin dependencies.  Thus, current versions are now:

```
'io.swagger:swagger-codegen:2.2.3'
'io.swagger:swagger-parser:1.0.32'
'io.swagger:swagger-compat-spec-parser:1.0.32'
```

There are multiple transitive dependencies that have security vulnerabilities fixed in the above versions:

For instance, swagger-compat-spec-parser now uses updated org.apache.httpcomponents:httpclient v4.5.2

This addresses [CVE-2014-3577](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-3577) and [CVE-2015-5262](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-5262)

Additionally:

jackson-databind v2.8.9  (this one has CVSS 3.0 score of 7.5).   See FasterXML/jackson-databind#1599
logback-classic v1.2.3
etc

It does not matter if there is (or is not) real exposure to any of these CVE... they still lead to threat alerts being generated by security analysis software such as Nexus IQ.
